% Author: Surya Kiran Akkaladevi
% Wright State University
% Thesis Report Format for Wright State Students
% Dedicated to my advisor Dr. Henry Chen and all student researchers of Wright State


\input{report.cls}\relax 
\usepackage{setspace}
\doublespace
\usepackage{lipsum}
\usepackage {adjustbox}
\usepackage{amsmath}
\usepackage{siunitx}
\usepackage[section]{placeins}
%\usepackage[utf8x]{inputenc}
\usepackage{graphicx}
%\usepackage{natbib}


\usepackage{standalone}
 
%\usepackage[noadjust]{cite}


\hyphenpenalty = 10000
\exhyphenpenalty = 10000

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Page Margins
\usepackage{geometry}
 \geometry{
 letterpaper,
 total={8.5in,11in},
 left=1.5in,
 right=1in,
 top=1in,
 bottom=1in,
 }
 
 \footskip = 12 pt
 
% \headheight=12 pt



\renewcommand\bibname{\normalfont\Large\centering\bfseries REFERENCES}


%%%%%%%%%%%%%Define Chapter headings
\usepackage{titlesec}

\titleformat{\chapter}
  {\normalfont\Large\centering\bfseries}{\thechapter}{1em}{}
\titleformat{\section}
  {\normalfont\large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}
  {\normalfont\large\bfseries}{\thesubsection}{1em}{}


\titlespacing*{\chapter}{0pt}{50pt}{0pt}
\titlespacing*{\section}{0pt}{0pt}{0pt}
\titlespacing*{\subsection}{0pt}{0pt}{0pt}

%%\titlespacing*{\chapter}{0pt}{3.5ex plus 1ex minus .2ex}{2.3ex plus .2ex}



%%%%%%paragraph spaceing

\setlength{\parindent}{2em}
\setlength{\parskip}{1em}

 
 
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% packages
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{indentfirst}

% begin your doc here

